version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - 4444:3306
    restart: always
  go-bot:
    image: golang:latest
    container_name: test-go-bot
    volumes:
      - ./bot:/bot
    working_dir: /bot
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: always
    command: go run /bot/.
